### ISSUE TITLE
I can't get this to work

### ISSUE THREAD

**Issue by insanity54** [AntumMT/mod-lighted_helmets#3]
Hi thanks for this mod! I really like the idea, but I wasn't able to get it to work in game.  I have installed on minetest server 5.6.1 along with the dependencies.

I see the mod getting loaded in the server console.

```
Oct 23 14:41:35 155.138.229.163 minetestserver[294688]: 2022-10-23 14:41:35: INFO[Main]: Mod "wielded_light" loaded after 2 ms
Oct 23 14:41:35 155.138.229.163 minetestserver[294688]: 2022-10-23 14:41:35: INFO[Main]: Mod "3d_armor_light" loaded after 0 ms
Oct 23 14:41:36 155.138.229.163 minetestserver[294688]: 2022-10-23 14:41:36: INFO[Main]: Mod "lighted_helmets" loaded after 0 ms
```

I copied the crafting recipe, but I'm not seeing a lighted helmet as a craftable option.

![screenshot_20221023_143329](https://user-images.githubusercontent.com/670375/197419883-87052dc1-2cd9-450a-937f-83e35847be4f.png)

Is there something obvious that I'm doing wrong?

**Comment by AntumDeluge** [comment]
`3d_armor` recently moved its armor types items into separate mods (`armor_bronze`, `armor_mithril`, `armor_diamond`, etc.). The problem is that `lighted_helmets` only depends on `3d_armor`. So if the individual armor type mods are loaded after `lighted_helmets` the new lighted helmets & craft recipes aren't registered. This can be worked around by adding the armor type mods to `optional_depends` in `mod.conf`:

```
optional_depends = armor_admin, armor_bronze, armor_cactus, armor_crystal, armor_diamond, armor_gold, armor_mithril, armor_nether, armor_steel, armor_wood
```

I will try to get a fix out when I have time. It will probably just postpone registration until after all mods are loaded so I don't have to permanently add each individual armor mod to `optional_depends`.
